# Generated by Django 2.0.4 on 2018-04-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=10)),
                ('filename', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('area', models.CharField(max_length=5)),
                ('tariff', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='usage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User', to_field='user_id'),
        ),
    ]
